######################################################################
# Automatically generated by qmake (2.01a) Mon May 27 16:14:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CXXFLAGS += -Wall

# Input
SOURCES += main.cpp netget.cpp stdinThread.cpp 
HEADERS += netget.h stdinThread.h 
